# This file is managed by the 'files-dbt' file bundle and updated automatically when `meltano upgrade` is run.
# To prevent any manual changes from being overwritten, remove the file bundle from `meltano.yml` or disable automatic updates:
#     meltano config --plugin-type=files files-dbt set _update transform/profile/profiles.yml false

flags:
  send_anonymous_usage_stats: False
  use_colors: True
meltano:
  target: "{{ env_var('DBT_TARGET') }}"
  outputs:
    snowflake:
      type: snowflake
      threads: 2
      account: "{{ env_var('TARGET_SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('TARGET_SNOWFLAKE_USER') }}"
      password: "{{ env_var('TARGET_SNOWFLAKE_PASSWORD') }}"
      private_key: "{{ env_var('TARGET_SNOWFLAKE_PRIVATE_KEY') }}"
      private_key_passphrase: "{{ env_var('TARGET_SNOWFLAKE_PRIVATE_KEY_PASSPHRASE', '') }}"
      role: "{{ env_var('TARGET_SNOWFLAKE_ROLE') }}"
      database: "{{ env_var('TARGET_SNOWFLAKE_DATABASE') }}"
      warehouse: "{{ env_var('TARGET_SNOWFLAKE_WAREHOUSE') }}"
      schema: "{{ env_var('TARGET_SNOWFLAKE_SCHEMA') }}"
    postgres:
      type: postgres
      threads: 2
      host: "{{ env_var('TARGET_POSTGRES_HOST') }}"
      port: "{{ env_var('TARGET_POSTGRES_PORT') | int }}"
      user: "{{ env_var('TARGET_POSTGRES_USER') }}"
      pass: "{{ env_var('TARGET_POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('TARGET_POSTGRES_DBNAME') }}"
      schema: "{{ env_var('TARGET_POSTGRES_SCHEMA') }}"
    postgres_transferwise:
      type: postgres
      threads: 2
      host: "{{ env_var('TARGET_POSTGRES_HOST') }}"
      port: "{{ env_var('TARGET_POSTGRES_PORT') | int }}"
      user: "{{ env_var('TARGET_POSTGRES_USER') }}"
      pass: "{{ env_var('TARGET_POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('TARGET_POSTGRES_DBNAME') }}"
      schema: "{{ env_var('TARGET_POSTGRES_DEFAULT_TARGET_SCHEMA') }}"
    bigquery:
      type: bigquery
      threads: 2
      method: service-account-json
      project: "{{ env_var('TARGET_BIGQUERY_PROJECT') }}"
      dataset: "{{ env_var('TARGET_BIGQUERY_DATASET') }}"
      keyfile_json: "{{ env_var('TARGET_BIGQUERY_CREDENTIALS_JSON') | as_native }}"
elementary:
  target: "{{ env_var('DBT_TARGET') }}"
  outputs:
    snowflake:
      type: snowflake
      threads: 2
      account: "{{ env_var('TARGET_SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('TARGET_SNOWFLAKE_USERNAME') }}"
      password: "{{ env_var('TARGET_SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('TARGET_SNOWFLAKE_ROLE') }}"
      database: "{{ env_var('TARGET_SNOWFLAKE_DATABASE') }}"
      warehouse: "{{ env_var('TARGET_SNOWFLAKE_WAREHOUSE') }}"
      schema: "matatika_test_results"
    postgres:
      type: postgres
      threads: 2
      host: "{{ env_var('TARGET_POSTGRES_HOST') }}"
      port: "{{ env_var('TARGET_POSTGRES_PORT') | int }}"
      user: "{{ env_var('TARGET_POSTGRES_USER') }}"
      pass: "{{ env_var('TARGET_POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('TARGET_POSTGRES_DBNAME') }}"
      schema: "matatika_test_results"
    postgres_transferwise:
      type: postgres
      threads: 2
      host: "{{ env_var('TARGET_POSTGRES_HOST') }}"
      port: "{{ env_var('TARGET_POSTGRES_PORT') | int }}"
      user: "{{ env_var('TARGET_POSTGRES_USER') }}"
      pass: "{{ env_var('TARGET_POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('TARGET_POSTGRES_DBNAME') }}"
      schema: "matatika_test_results"
    bigquery:
      type: bigquery
      threads: 2
      method: service-account-json
      project: "{{ env_var('TARGET_BIGQUERY_PROJECT') }}"
      dataset: "matatika_test_results"
      keyfile_json: "{{ env_var('TARGET_BIGQUERY_CREDENTIALS_JSON') | as_native }}"
